### ISSUE TITLE
Not rebuild .html files after change .njk files

### ISSUE THREAD

**Issue by alimzhanovamir** [bnku/webpack-nunjucks-sass-template#1]
Hi!
I launch the webpack with the `yarn dev` command and when the .njk file is changed, webpack don’t rebuild the project. Only i change index.js, webpack rebuild the project.

Привет!
Когда запускаю `yarn  dev`, то при изменении в .njk файлах не происходит пересборка .html

**Comment by bnku** [comment]
Use `npm run dev`. package not tested with yarn.

**Comment by alimzhanovamir** [comment]
> Use `npm run dev`. package not tested with yarn.

Всё так же, выполняю `npm run dev`, запускается сервер, билдятся файлы. А когда открываю, к примеру, index.njk и редактирую, то ничего не происходит. А вот если изменить index.js, то сборка пересобирается.

**Comment by bnku** [comment]
![webpack-njk](https://user-images.githubusercontent.com/2696333/60212230-61b8cd80-9869-11e9-93e3-e3408f32a086.gif)
все работает. смотри в логах какие варнинги есть и компилируется ли сам билд после сохранения njk.

**Comment by alimzhanovamir** [comment]
> ![webpack-njk](https://user-images.githubusercontent.com/2696333/60212230-61b8cd80-9869-11e9-93e3-e3408f32a086.gif)
> все работает. смотри в логах какие варнинги есть и компилируется ли сам билд после сохранения njk.

Скачал архив, распаковал, `npm install`, `npm run dev` и всё так же. После сохранения в .njk не компилируется.
![Выбрать npm 2019-06-27 00 33 52](https://user-images.githubusercontent.com/31186418/60216964-296abc80-9874-11e9-9402-ea55b8e285a3.png)
![Выбрать npm 2019-06-27 00 34 28](https://user-images.githubusercontent.com/31186418/60216969-2ec80700-9874-11e9-89da-915d65c1c7f1.png)




node: 10.16.0
npm: 6.9.0

**Comment by alimzhanovamir** [comment]
Не работает на windows, проблема в [плагине](https://github.com/itgalaxy/nunjucks-webpack-plugin/issues/7)
